apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-ref: d62d6ac205fdddfdf3d4a3964e1585d13211b616
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/nextjs-app-tkaatz.git
  labels:
    app: tkaatz-next
    app.kubernetes.io/instance: tkaatz-next
    app.kubernetes.io/name: tkaatz-next-next-sample-app
    app.openshift.io/runtime: js
  name: nextjs-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: tkaatz-next
    app.kubernetes.io/instance: tkaatz-next
    app.kubernetes.io/name: tkaatz-next-next-sample-app
    app.openshift.io/runtime: js
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-ref: d62d6ac205fdddfdf3d4a3964e1585d13211b616
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/nextjs-app-tkaatz.git
  labels:
    app: tkaatz-next
    app.kubernetes.io/instance: tkaatz-next
    app.kubernetes.io/name: tkaatz-next-next-sample-app
    app.openshift.io/runtime: js
  name: nextjs-app
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tkaatz-next
      app.kubernetes.io/instance: tkaatz-next
      app.kubernetes.io/name: tkaatz-next-next-sample-app
      app.openshift.io/runtime: js
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-ref: d62d6ac205fdddfdf3d4a3964e1585d13211b616
        app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/nextjs-app-tkaatz.git
      labels:
        app: tkaatz-next
        app.kubernetes.io/instance: tkaatz-next
        app.kubernetes.io/name: tkaatz-next-next-sample-app
        app.openshift.io/runtime: js
    spec:
      containers:
      - env:
        - name: INGRESS_HOST
        - name: PROTOCOLS
        - name: LOG_LEVEL
          value: debug
        image: quay.io/tkaatz/next-sample:d62d6ac205fdddfdf3d4a3964e1585d13211b616
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: nextjs-app
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/vcs-ref: d62d6ac205fdddfdf3d4a3964e1585d13211b616
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/nextjs-app-tkaatz.git
    argocd.argoproj.io/sync-options: Validate=false
    openshift.io/host.generated: "true"
  labels:
    app: tkaatz-next
    app.kubernetes.io/instance: tkaatz-next
    app.kubernetes.io/name: tkaatz-next-next-sample-app
    app.openshift.io/runtime: js
  name: nextjs-app
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: nextjs-app
    weight: 100
  wildcardPolicy: None
