apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-ref: 94786876393ffe2111d4a41a947c7f163ec46c9b
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/emea5-squad3-project.git
  labels:
    app: emea5-squad3-project
    app.kubernetes.io/instance: emea5-squad3-project
    app.kubernetes.io/name: emea5-squad3-project-emea5-squad3
    app.openshift.io/runtime: js
  name: django-blog-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: emea5-squad3-project
    app.kubernetes.io/instance: emea5-squad3-project
    app.kubernetes.io/name: emea5-squad3-project-emea5-squad3
    app.openshift.io/runtime: js
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-ref: 94786876393ffe2111d4a41a947c7f163ec46c9b
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/emea5-squad3-project.git
  labels:
    app: emea5-squad3-project
    app.kubernetes.io/instance: emea5-squad3-project
    app.kubernetes.io/name: emea5-squad3-project-emea5-squad3
    app.openshift.io/runtime: js
  name: django-blog-app
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: emea5-squad3-project
      app.kubernetes.io/instance: emea5-squad3-project
      app.kubernetes.io/name: emea5-squad3-project-emea5-squad3
      app.openshift.io/runtime: js
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-ref: 94786876393ffe2111d4a41a947c7f163ec46c9b
        app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/emea5-squad3-project.git
      labels:
        app: emea5-squad3-project
        app.kubernetes.io/instance: emea5-squad3-project
        app.kubernetes.io/name: emea5-squad3-project-emea5-squad3
        app.openshift.io/runtime: js
    spec:
      containers:
      - env:
        - name: INGRESS_HOST
        - name: PROTOCOLS
        - name: LOG_LEVEL
          value: debug
        image: quay.io/lucilejerber/emea5-squad3:94786876393ffe2111d4a41a947c7f163ec46c9b
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: django-blog-app
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/vcs-ref: 94786876393ffe2111d4a41a947c7f163ec46c9b
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/emea5-squad3-project.git
    argocd.argoproj.io/sync-options: Validate=false
    openshift.io/host.generated: "true"
  labels:
    app: emea5-squad3-project
    app.kubernetes.io/instance: emea5-squad3-project
    app.kubernetes.io/name: emea5-squad3-project-emea5-squad3
    app.openshift.io/runtime: js
  name: django-blog-app
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: django-blog-app
    weight: 100
  wildcardPolicy: None
