apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-ref: 940b837ce6fa5619eb03a8ca6d9fca0906c4fb1d
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/emea-5-project-squad2-be.git
  labels:
    app: backend
    app.kubernetes.io/instance: squad2-project-backend-inst
    app.kubernetes.io/name: squad2-project-backend
    app.openshift.io/runtime: js
  name: backend
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: backend
    app.kubernetes.io/instance: squad2-project-backend-inst
    app.kubernetes.io/name: squad2-project-backend
    app.openshift.io/runtime: js
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-ref: 940b837ce6fa5619eb03a8ca6d9fca0906c4fb1d
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/emea-5-project-squad2-be.git
  labels:
    app: backend
    app.kubernetes.io/instance: squad2-project-backend-inst
    app.kubernetes.io/name: squad2-project-backend
    app.openshift.io/runtime: js
  name: backend
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: backend
      app.kubernetes.io/instance: squad2-project-backend-inst
      app.kubernetes.io/name: squad2-project-backend
      app.openshift.io/runtime: js
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-ref: 940b837ce6fa5619eb03a8ca6d9fca0906c4fb1d
        app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/emea-5-project-squad2-be.git
      labels:
        app: backend
        app.kubernetes.io/instance: squad2-project-backend-inst
        app.kubernetes.io/name: squad2-project-backend
        app.openshift.io/runtime: js
    spec:
      containers:
      - env:
        - name: INGRESS_HOST
        - name: PROTOCOLS
        - name: LOG_LEVEL
          value: debug
        image: quay.io/tkaatz/squad2-be:940b837ce6fa5619eb03a8ca6d9fca0906c4fb1d
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: express-sample-app
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/vcs-ref: 940b837ce6fa5619eb03a8ca6d9fca0906c4fb1d
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/emea-5-project-squad2-be.git
    argocd.argoproj.io/sync-options: Validate=false
    openshift.io/host.generated: "true"
  labels:
    app: backend
    app.kubernetes.io/instance: squad2-project-backend-inst
    app.kubernetes.io/name: squad2-project-backend
    app.openshift.io/runtime: js
  name: backend
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: backend
    weight: 100
  wildcardPolicy: None
