apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-ref: c8047cc28c7119c3aac44dbf313917ec31b676c2
    app.openshift.io/vcs-uri: https://github.com/phthom/next
  labels:
    app: phthom
    app.kubernetes.io/instance: phthom
    app.kubernetes.io/name: phthom-next
    app.openshift.io/runtime: js
  name: next
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: phthom
    app.kubernetes.io/instance: phthom
    app.kubernetes.io/name: phthom-next
    app.openshift.io/runtime: js
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-ref: c8047cc28c7119c3aac44dbf313917ec31b676c2
    app.openshift.io/vcs-uri: https://github.com/phthom/next
  labels:
    app: phthom
    app.kubernetes.io/instance: phthom
    app.kubernetes.io/name: phthom-next
    app.openshift.io/runtime: js
  name: next
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: phthom
      app.kubernetes.io/instance: phthom
      app.kubernetes.io/name: phthom-next
      app.openshift.io/runtime: js
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-ref: c8047cc28c7119c3aac44dbf313917ec31b676c2
        app.openshift.io/vcs-uri: https://github.com/phthom/next
      labels:
        app: phthom
        app.kubernetes.io/instance: phthom
        app.kubernetes.io/name: phthom-next
        app.openshift.io/runtime: js
    spec:
      containers:
      - env:
        - name: INGRESS_HOST
        - name: PROTOCOLS
        - name: LOG_LEVEL
          value: debug
        image: quay.io/phthom0/next:c8047cc28c7119c3aac44dbf313917ec31b676c2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: next
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/vcs-ref: c8047cc28c7119c3aac44dbf313917ec31b676c2
    app.openshift.io/vcs-uri: https://github.com/phthom/next
    argocd.argoproj.io/sync-options: Validate=false
    openshift.io/host.generated: "true"
  labels:
    app: phthom
    app.kubernetes.io/instance: phthom
    app.kubernetes.io/name: phthom-next
    app.openshift.io/runtime: js
  name: next
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: next
    weight: 100
  wildcardPolicy: None
