apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-ref: 7681e6b7a21dbaab8f12e3237d1a9c1e2ea75705
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/dmi-vlasenko-react-e2e
  labels:
    app: dmi-v-react-e2e
    app.kubernetes.io/instance: dmi-v-react-e2e
    app.kubernetes.io/name: dmi-v-react-e2e-dmi-v-react-e2e
    app.openshift.io/runtime: js
  name: express-sample-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: dmi-v-react-e2e
    app.kubernetes.io/instance: dmi-v-react-e2e
    app.kubernetes.io/name: dmi-v-react-e2e-dmi-v-react-e2e
    app.openshift.io/runtime: js
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-ref: 7681e6b7a21dbaab8f12e3237d1a9c1e2ea75705
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/dmi-vlasenko-react-e2e
  labels:
    app: dmi-v-react-e2e
    app.kubernetes.io/instance: dmi-v-react-e2e
    app.kubernetes.io/name: dmi-v-react-e2e-dmi-v-react-e2e
    app.openshift.io/runtime: js
  name: express-sample-app
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: dmi-v-react-e2e
      app.kubernetes.io/instance: dmi-v-react-e2e
      app.kubernetes.io/name: dmi-v-react-e2e-dmi-v-react-e2e
      app.openshift.io/runtime: js
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-ref: 7681e6b7a21dbaab8f12e3237d1a9c1e2ea75705
        app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/dmi-vlasenko-react-e2e
      labels:
        app: dmi-v-react-e2e
        app.kubernetes.io/instance: dmi-v-react-e2e
        app.kubernetes.io/name: dmi-v-react-e2e-dmi-v-react-e2e
        app.openshift.io/runtime: js
    spec:
      containers:
      - env:
        - name: INGRESS_HOST
        - name: PROTOCOLS
        - name: LOG_LEVEL
          value: debug
        image: quay.io/dmiv/dmi-v-react-e2e:7681e6b7a21dbaab8f12e3237d1a9c1e2ea75705
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: express-sample-app
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/vcs-ref: 7681e6b7a21dbaab8f12e3237d1a9c1e2ea75705
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/dmi-vlasenko-react-e2e
    argocd.argoproj.io/sync-options: Validate=false
    openshift.io/host.generated: "true"
  labels:
    app: dmi-v-react-e2e
    app.kubernetes.io/instance: dmi-v-react-e2e
    app.kubernetes.io/name: dmi-v-react-e2e-dmi-v-react-e2e
    app.openshift.io/runtime: js
  name: express-sample-app
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: express-sample-app
    weight: 100
  wildcardPolicy: None
