apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-ref: 9dff7026455ac2fe0769287f1c20138cc8996787
    app.openshift.io/vcs-uri: https://github.com/HendrikJLoe/hendrik-e2e-app
  labels:
    app: hendrik-loeffel-sample-app-production
    app.kubernetes.io/instance: hendrik-loeffel-sample-app-production
    app.kubernetes.io/name: hendrik-loeffel-sample-app-production-hendrik-e2e-assignment
    app.openshift.io/runtime: js
  name: express-sample-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: hendrik-loeffel-sample-app-production
    app.kubernetes.io/instance: hendrik-loeffel-sample-app-production
    app.kubernetes.io/name: hendrik-loeffel-sample-app-production-hendrik-e2e-assignment
    app.openshift.io/runtime: js
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-ref: 9dff7026455ac2fe0769287f1c20138cc8996787
    app.openshift.io/vcs-uri: https://github.com/HendrikJLoe/hendrik-e2e-app
  labels:
    app: hendrik-loeffel-sample-app-production
    app.kubernetes.io/instance: hendrik-loeffel-sample-app-production
    app.kubernetes.io/name: hendrik-loeffel-sample-app-production-hendrik-e2e-assignment
    app.openshift.io/runtime: js
  name: hendrik-e2e-assignment
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hendrik-loeffel-sample-app-production
      app.kubernetes.io/instance: hendrik-loeffel-sample-app-production
      app.kubernetes.io/name: hendrik-loeffel-sample-app-production-hendrik-e2e-assignment
      app.openshift.io/runtime: js
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-ref: 9dff7026455ac2fe0769287f1c20138cc8996787
        app.openshift.io/vcs-uri: https://github.com/HendrikJLoe/hendrik-e2e-app
      labels:
        app: hendrik-loeffel-sample-app-production
        app.kubernetes.io/instance: hendrik-loeffel-sample-app-production
        app.kubernetes.io/name: hendrik-loeffel-sample-app-production-hendrik-e2e-assignment
        app.openshift.io/runtime: js
    spec:
      containers:
      - env:
        - name: INGRESS_HOST
        - name: PROTOCOLS
        - name: LOG_LEVEL
          value: debug
        image: quay.io/hendrik_loeffel/e2e-assignment:9dff7026455ac2fe0769287f1c20138cc8996787
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: express-sample-app
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/vcs-ref: 9dff7026455ac2fe0769287f1c20138cc8996787
    app.openshift.io/vcs-uri: https://github.com/HendrikJLoe/hendrik-e2e-app
  labels:
    app: hendrik-loeffel-sample-app-production
    app.kubernetes.io/instance: hendrik-loeffel-sample-app-production
    app.kubernetes.io/name: hendrik-loeffel-sample-app-production-hendrik-e2e-assignment
    app.openshift.io/runtime: js
  name: express-sample-app
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: express-sample-app
    weight: 100
  wildcardPolicy: None
