apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-ref: 8bd27f37587091d64e9185a402e4ce679f0e77e0
    app.openshift.io/vcs-uri: https://github.com/alexseymour1997/alex-jignesh-e2e.git
  labels:
    app: alex-jignesh-e2e
    app.kubernetes.io/instance: alex-jignesh-e2e
    app.kubernetes.io/name: alex-jignesh-e2e-next-app-e2e
    app.openshift.io/runtime: js
  name: express-sample-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: alex-jignesh-e2e
    app.kubernetes.io/instance: alex-jignesh-e2e
    app.kubernetes.io/name: alex-jignesh-e2e-next-app-e2e
    app.openshift.io/runtime: js
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-ref: 8bd27f37587091d64e9185a402e4ce679f0e77e0
    app.openshift.io/vcs-uri: https://github.com/alexseymour1997/alex-jignesh-e2e.git
  labels:
    app: alex-jignesh-e2e
    app.kubernetes.io/instance: alex-jignesh-e2e
    app.kubernetes.io/name: alex-jignesh-e2e-next-app-e2e
    app.openshift.io/runtime: js
  name: express-sample-app
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: alex-jignesh-e2e
      app.kubernetes.io/instance: alex-jignesh-e2e
      app.kubernetes.io/name: alex-jignesh-e2e-next-app-e2e
      app.openshift.io/runtime: js
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-ref: 8bd27f37587091d64e9185a402e4ce679f0e77e0
        app.openshift.io/vcs-uri: https://github.com/alexseymour1997/alex-jignesh-e2e.git
      labels:
        app: alex-jignesh-e2e
        app.kubernetes.io/instance: alex-jignesh-e2e
        app.kubernetes.io/name: alex-jignesh-e2e-next-app-e2e
        app.openshift.io/runtime: js
    spec:
      containers:
      - env:
        - name: INGRESS_HOST
        - name: PROTOCOLS
        - name: LOG_LEVEL
          value: debug
        image: quay.io/alexander_seymour_ibm/alex-jignesh-e2e:8bd27f37587091d64e9185a402e4ce679f0e77e0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: express-sample-app
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/vcs-ref: 8bd27f37587091d64e9185a402e4ce679f0e77e0
    app.openshift.io/vcs-uri: https://github.com/alexseymour1997/alex-jignesh-e2e.git
    argocd.argoproj.io/sync-options: Validate=false
    openshift.io/host.generated: "true"
  labels:
    app: alex-jignesh-e2e
    app.kubernetes.io/instance: alex-jignesh-e2e
    app.kubernetes.io/name: alex-jignesh-e2e-next-app-e2e
    app.openshift.io/runtime: js
  name: express-sample-app
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: express-sample-app
    weight: 100
  wildcardPolicy: None
