apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-ref: 1d70ea7a05bafe68429ddc17ec917b81b6ad0ccd
    app.openshift.io/vcs-uri: https://github.com/FlorianSchaechter/tekton-e2e
  labels:
    app: florian-schaechter-tekton-e2e-assignment
    app.kubernetes.io/instance: florian-schaechter-tekton-e2e-assignment
    app.kubernetes.io/name: florian-schaechter-tekton-e2e-assignment-tekton-e2e-app
    app.openshift.io/runtime: js
  name: tekton-e2e-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: florian-schaechter-tekton-e2e-assignment
    app.kubernetes.io/instance: florian-schaechter-tekton-e2e-assignment
    app.kubernetes.io/name: florian-schaechter-tekton-e2e-assignment-tekton-e2e-app
    app.openshift.io/runtime: js
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-ref: 1d70ea7a05bafe68429ddc17ec917b81b6ad0ccd
    app.openshift.io/vcs-uri: https://github.com/FlorianSchaechter/tekton-e2e
  labels:
    app: florian-schaechter-tekton-e2e-assignment
    app.kubernetes.io/instance: florian-schaechter-tekton-e2e-assignment
    app.kubernetes.io/name: florian-schaechter-tekton-e2e-assignment-tekton-e2e-app
    app.openshift.io/runtime: js
  name: tekton-e2e-app
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: florian-schaechter-tekton-e2e-assignment
      app.kubernetes.io/instance: florian-schaechter-tekton-e2e-assignment
      app.kubernetes.io/name: florian-schaechter-tekton-e2e-assignment-tekton-e2e-app
      app.openshift.io/runtime: js
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-ref: 1d70ea7a05bafe68429ddc17ec917b81b6ad0ccd
        app.openshift.io/vcs-uri: https://github.com/FlorianSchaechter/tekton-e2e
      labels:
        app: florian-schaechter-tekton-e2e-assignment
        app.kubernetes.io/instance: florian-schaechter-tekton-e2e-assignment
        app.kubernetes.io/name: florian-schaechter-tekton-e2e-assignment-tekton-e2e-app
        app.openshift.io/runtime: js
    spec:
      containers:
      - env:
        - name: INGRESS_HOST
        - name: PROTOCOLS
        - name: LOG_LEVEL
          value: debug
        image: quay.io/florian_schaechter/tekto-e2e:1d70ea7a05bafe68429ddc17ec917b81b6ad0ccd
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: tekton-e2e-app
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/vcs-ref: 1d70ea7a05bafe68429ddc17ec917b81b6ad0ccd
    app.openshift.io/vcs-uri: https://github.com/FlorianSchaechter/tekton-e2e
    argocd.argoproj.io/sync-options: Validate=false
    openshift.io/host.generated: "true"
  labels:
    app: florian-schaechter-tekton-e2e-assignment
    app.kubernetes.io/instance: florian-schaechter-tekton-e2e-assignment
    app.kubernetes.io/name: florian-schaechter-tekton-e2e-assignment-tekton-e2e-app
    app.openshift.io/runtime: js
  name: tekton-e2e-app
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: tekton-e2e-app
    weight: 100
  wildcardPolicy: None
